/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Vistas;

import Modelo.Cliente;
import Modelo.ClienteTicket;
import Modelo.Cuota;
import Modelo.Prestamo;
import Modelo.SaldoCliente;
import ModeloDao.ClienteDao;
import ModeloDao.CobradorDao;
import ModeloDao.CuotaDao;
import ModeloDao.PrestamoDao;
import ModeloDao.SaldoDao;
import configuracion.ColorearCelda;
import configuracion.ColorearFilas;
import configuracion.ColorearHeaderCuotaTikect;
import configuracion.ColorearHeaderResumenCuenta;
import configuracion.Fecha;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.JTextArea;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableCellRenderer;
import javax.swing.table.TableRowSorter;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.data.JRBeanCollectionDataSource;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author santi
 */
public class GenerarTicket extends javax.swing.JInternalFrame {

    //DefaultTableModel modelo = new DefaultTableModel();
    DefaultTableModel modelo3 = new DefaultTableModel();
    ClienteDao clidao = new ClienteDao();
    Prestamo prestamo = new Prestamo();
    CuotaDao cuodao = new CuotaDao();
    SaldoDao saldodao = new SaldoDao();
    PrestamoDao predao = new PrestamoDao();
    CobradorDao cobradordao = new CobradorDao();
    List<Cuota> lista;
    List<Cliente> listaclientes = clidao.Listar();
    List<ClienteTicket> clientestick = new ArrayList();
    ColorearHeaderResumenCuenta CHRC = new ColorearHeaderResumenCuenta();
    ColorearHeaderCuotaTikect ColorHeaderTicket = new ColorearHeaderCuotaTikect();
    TableRowSorter trs;
    int id;
    String nombre;
    String apellido;
    String telefono;
    String direccion;
    double montocuota;
    String importeprestado;
    ColorearFilas colorear = new ColorearFilas();
    String columnas[] = {"nroprestamo", "id cuota", "monto", "fecha pago", "estado", "nrocuota", "accion"};
    boolean ColumnasEditables[] = {false, false, false, false, false, false, true};
    Class tipo[] = new Class[]{java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class,
        java.lang.Object.class, java.lang.Object.class,
        java.lang.Boolean.class};
    DefaultTableModel modelo = new DefaultTableModel();
    DefaultTableModel modelo2 = new DefaultTableModel() {
        public boolean isCellEditable(int row, int col) {
            return ColumnasEditables[col];
        }

        public Class getColumnClass(int index) {
            return tipo[index];
        }
    };

    public GenerarTicket() {
        initComponents();

        tablaticket.getTableHeader().setDefaultRenderer(ColorHeaderTicket);

        Fecha fec = new Fecha(); //instanciamos la clase fecha y obtenemos en forma de string
        String fecact = fec.Fecha();

        fechahoy.setText(fecact);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        fechahoy = new javax.swing.JLabel();
        nada = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        Desde = new com.toedter.calendar.JDateChooser();
        hasta = new com.toedter.calendar.JDateChooser();
        jLabel8 = new javax.swing.JLabel();
        porcentajecobrador = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        nafta = new javax.swing.JTextField();
        porcentajepago = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        TotalCobrador = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaticket = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        GenerarTicketAuto = new javax.swing.JButton();
        btneliminar = new javax.swing.JButton();
        btnImprimirTicket = new javax.swing.JButton();

        setClosable(true);
        setMaximizable(true);

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.setForeground(new java.awt.Color(102, 153, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 204, 255));
        jLabel1.setText("Tickets");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(153, 255, 255));
        jLabel4.setText("FECHA:");

        fechahoy.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        fechahoy.setForeground(new java.awt.Color(153, 255, 255));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(437, 437, 437)
                .addComponent(jLabel4)
                .addGap(41, 41, 41)
                .addComponent(fechahoy)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel4)
                    .addComponent(fechahoy))
                .addGap(0, 9, Short.MAX_VALUE))
        );

        nada.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Clientes", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        jLabel5.setText("De domingo");

        jLabel6.setText("a sabado:");

        jLabel7.setText("Tickets Automatico");

        jLabel8.setText("Porcentaje cobrador:");

        porcentajecobrador.setText("porcentaje cobrador");

        jLabel9.setText("Porcentaje de pago");

        jLabel10.setText("Nafta :");

        nafta.setText("500");

        porcentajepago.setText("0.08");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel11.setText("TOTAL : ");

        TotalCobrador.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        TotalCobrador.setForeground(new java.awt.Color(102, 153, 255));
        TotalCobrador.setText("totalcobrador");

        javax.swing.GroupLayout nadaLayout = new javax.swing.GroupLayout(nada);
        nada.setLayout(nadaLayout);
        nadaLayout.setHorizontalGroup(
            nadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(nadaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(nadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, nadaLayout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(TotalCobrador, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22))
                    .addGroup(nadaLayout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addGroup(nadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(nadaLayout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(22, 22, 22)
                                .addComponent(porcentajecobrador, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(nadaLayout.createSequentialGroup()
                                .addGroup(nadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(nadaLayout.createSequentialGroup()
                                        .addGap(72, 72, 72)
                                        .addComponent(jLabel7))
                                    .addGroup(nadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(nadaLayout.createSequentialGroup()
                                            .addComponent(jLabel10)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(nafta, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, nadaLayout.createSequentialGroup()
                                            .addComponent(jLabel9)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(porcentajepago, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, nadaLayout.createSequentialGroup()
                                            .addGroup(nadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel5)
                                                .addComponent(jLabel6))
                                            .addGap(28, 28, 28)
                                            .addGroup(nadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(hasta, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(Desde, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                .addGap(0, 23, Short.MAX_VALUE)))
                        .addContainerGap())))
        );
        nadaLayout.setVerticalGroup(
            nadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, nadaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addGap(28, 28, 28)
                .addGroup(nadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5)
                    .addComponent(Desde, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(nadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6)
                    .addComponent(hasta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(nadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(porcentajepago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(nadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nafta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addGap(29, 29, 29)
                .addGroup(nadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(porcentajecobrador))
                .addGap(25, 25, 25)
                .addGroup(nadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(TotalCobrador))
                .addContainerGap(65, Short.MAX_VALUE))
        );

        tablaticket.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "nombre", "apellido", "saldo pagado", "saldo debe", "atraso", "total ", "fecha limite pago", "monto cuota", "nro cuota"
            }
        ));
        jScrollPane2.setViewportView(tablaticket);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Lista de clientes para cobrar");

        GenerarTicketAuto.setBackground(new java.awt.Color(51, 153, 255));
        GenerarTicketAuto.setForeground(new java.awt.Color(255, 255, 255));
        GenerarTicketAuto.setText("Generar Automatico");
        GenerarTicketAuto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GenerarTicketAutoActionPerformed(evt);
            }
        });

        btneliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/cancelar4.png"))); // NOI18N
        btneliminar.setText("eliminar");
        btneliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneliminarActionPerformed(evt);
            }
        });

        btnImprimirTicket.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/Print_icon-icons.com_73705.png"))); // NOI18N
        btnImprimirTicket.setText("imprimir");
        btnImprimirTicket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImprimirTicketActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(nada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(GenerarTicketAuto, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btneliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnImprimirTicket, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(251, 251, 251))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane2)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                        .addComponent(nada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnImprimirTicket)
                            .addComponent(btneliminar)
                            .addComponent(GenerarTicketAuto, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(44, 44, 44))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    void lipiartablacuotas() {
        for (int i = 0; i < modelo2.getRowCount(); i++) {
            modelo2.removeRow(i);
            i = i - 1;
        }
    }
    private void btnImprimirTicketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImprimirTicketActionPerformed
        try {
            JasperReport reporte = (JasperReport) JRLoader.loadObjectFromFile("C:\\Users\\santi\\Documents\\NetBeansProjects\\Prestamin\\src\\Reportes\\GenerarTicket.jasper");
            Map parametro = new HashMap();
            //parametro.put("nombre", nombre);
            //parametro.put("apellido", apellido);
            //parametro.put("telefono", telefono);
            parametro.put("fechaemision", fechahoy.getText());

            parametro.put("fondoimagen", "C:\\Users\\santi\\Documents\\NetBeansProjects\\Prestamin\\src\\Iconos\\Prestamin2.png");
            JasperPrint pirnt = JasperFillManager.fillReport(reporte, parametro, new JRBeanCollectionDataSource(clientestick));
            JasperViewer.viewReport(pirnt, false);
        } catch (JRException ex) {
            Logger.getLogger(RegistrarCobro2.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnImprimirTicketActionPerformed

    private void btneliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneliminarActionPerformed
        int selec = tablaticket.getSelectedRow();
        clientestick.remove(selec);
        modelo3.removeRow(selec);
    }//GEN-LAST:event_btneliminarActionPerformed

    private void GenerarTicketAutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GenerarTicketAutoActionPerformed

        limpiartablatickect();
        tickectautomaticos();
    }//GEN-LAST:event_GenerarTicketAutoActionPerformed
    void GenerarAtrasados(){
         modelo3 = (DefaultTableModel) tablaticket.getModel();
        String diaini = Integer.toString(Desde.getCalendar().get(Calendar.DAY_OF_MONTH));
        String mesini = Integer.toString(Desde.getCalendar().get(Calendar.MONTH) + 1);
        String yearini = Integer.toString(Desde.getCalendar().get(Calendar.YEAR));
        String fechainicial = yearini + "-" + mesini + "-" + diaini;


       
        List<ClienteTicket> lista2 = cuodao.BuscarCuotasAtradas(fechainicial);
        
        Object[] objeto = new Object[9];
         
        for (int i = 0; i < lista2.size(); i++) {
              Double sm = Double.parseDouble(lista2.get(i).getSaldomoroso());
            Double montocuota = Double.parseDouble(lista2.get(i).getMontocuota());
            //sumar = sumar + montocuota;
            //Double total = cuodao.calculartotalpagar(montocuota, sm);

            ClienteTicket cli_ticket = new ClienteTicket();
            cli_ticket.setNombre(lista2.get(i).getNombre());
            cli_ticket.setApellido(lista2.get(i).getApellido());
            cli_ticket.setTelefono(lista2.get(i).getTelefono());
            cli_ticket.setSaldopagado(lista2.get(i).getSaldopagado());
            cli_ticket.setSaldomoroso(lista2.get(i).getSaldomoroso());
            cli_ticket.setSaldodebe(lista2.get(i).getSaldodebe());
            cli_ticket.setImporteprestado(lista2.get(i).getImporteprestado());

            cli_ticket.setMontocuota(lista2.get(i).getSaldomoroso());
            cli_ticket.setNrocuota(lista2.get(i).getNrocuota());
            cli_ticket.setFechalimitepago(lista2.get(i).getFechalimitepago());
            cli_ticket.setTotal(lista2.get(i).getSaldomoroso());

            clientestick.add(cli_ticket);

            objeto[0] = lista2.get(i).getNombre();
            objeto[1] = lista2.get(i).getApellido();
            objeto[2] = lista2.get(i).getSaldopagado();
            objeto[3] = lista2.get(i).getSaldodebe();
            objeto[4] = lista2.get(i).getSaldomoroso();
            objeto[5] = 0.0;
            objeto[6] = lista2.get(i).getFechalimitepago();
            objeto[7] = lista2.get(i).getSaldomoroso();
            objeto[8] = lista2.get(i).getNrocuota();
            modelo3.addRow(objeto);

            tablaticket.setModel(modelo3);
        }
    }
    
 
    void tickectautomaticos() {
        modelo3 = (DefaultTableModel) tablaticket.getModel();
        String diaini = Integer.toString(Desde.getCalendar().get(Calendar.DAY_OF_MONTH));
        String mesini = Integer.toString(Desde.getCalendar().get(Calendar.MONTH) + 1);
        String yearini = Integer.toString(Desde.getCalendar().get(Calendar.YEAR));
        String fechainicial = yearini + "-" + mesini + "-" + diaini;

        String diafin = Integer.toString(hasta.getCalendar().get(Calendar.DAY_OF_MONTH));
        String mesfin = Integer.toString(hasta.getCalendar().get(Calendar.MONTH) + 1);
        String yearfin = Integer.toString(hasta.getCalendar().get(Calendar.YEAR));
        String fechafinal = yearfin + "-" + mesfin + "-" + diafin;

        Double porcentajecobra = cobradordao.PorcentajeCobrador(fechainicial, fechafinal);
        porcentajecobrador.setText((Double.toString(porcentajecobra)));

        List<ClienteTicket> lista = cuodao.BuscarCuotasPorRangos(fechainicial, fechafinal);
        List<ClienteTicket> lista2 = cuodao.BuscarCuotasAtradas(fechainicial);
        
        Object[] objeto = new Object[9];
        double sumar = 0;
        for (int i = 0; i < lista.size(); i++) {
            Double sm = Double.parseDouble(lista.get(i).getSaldomoroso());
            Double montocuota = Double.parseDouble(lista.get(i).getMontocuota());
            sumar = sumar + montocuota;
            //Double total = cuodao.calculartotalpagar(montocuota, sm);

            ClienteTicket cli_ticket = new ClienteTicket();
            cli_ticket.setNombre(lista.get(i).getNombre());
            cli_ticket.setApellido(lista.get(i).getApellido());
            cli_ticket.setTelefono(lista.get(i).getTelefono());
             cli_ticket.setDireccion(lista.get(i).getDireccion());
            
            cli_ticket.setSaldopagado(lista.get(i).getSaldopagado());
            cli_ticket.setSaldomoroso(lista.get(i).getSaldomoroso());
            cli_ticket.setSaldodebe(lista.get(i).getSaldodebe());
            cli_ticket.setImporteprestado(lista.get(i).getImporteprestado());

            cli_ticket.setMontocuota(lista.get(i).getMontocuota());
            cli_ticket.setNrocuota(lista.get(i).getNrocuota());
            cli_ticket.setFechalimitepago(lista.get(i).getFechalimitepago());
            cli_ticket.setTotal(Double.toString(montocuota));

            clientestick.add(cli_ticket);

            objeto[0] = lista.get(i).getNombre();
            objeto[1] = lista.get(i).getApellido();
            objeto[2] = lista.get(i).getSaldopagado();
            objeto[3] = lista.get(i).getSaldodebe();
            objeto[4] = lista.get(i).getSaldomoroso();
            objeto[5] = montocuota;
            objeto[6] = lista.get(i).getFechalimitepago();
            objeto[7] = lista.get(i).getMontocuota();
            objeto[8] = lista.get(i).getNrocuota();
            modelo3.addRow(objeto);

            tablaticket.setModel(modelo3);
        }
        
          
        
        
        for (int i = 0; i < lista2.size(); i++) {
              Double sm = Double.parseDouble(lista2.get(i).getSaldomoroso());
            Double montocuota = Double.parseDouble(lista2.get(i).getMontocuota());
            //sumar = sumar + montocuota;
            //Double total = cuodao.calculartotalpagar(montocuota, sm);

            ClienteTicket cli_ticket = new ClienteTicket();
            cli_ticket.setNombre(lista2.get(i).getNombre());
            cli_ticket.setApellido(lista2.get(i).getApellido());
            cli_ticket.setTelefono(lista2.get(i).getTelefono());
            cli_ticket.setSaldopagado(lista2.get(i).getSaldopagado());
            cli_ticket.setSaldomoroso(lista2.get(i).getSaldomoroso());
            cli_ticket.setSaldodebe(lista2.get(i).getSaldodebe());
            cli_ticket.setImporteprestado(lista2.get(i).getImporteprestado());

            cli_ticket.setMontocuota(lista2.get(i).getSaldomoroso());
            cli_ticket.setNrocuota(lista2.get(i).getNrocuota());
            cli_ticket.setFechalimitepago(lista2.get(i).getFechalimitepago());
            cli_ticket.setTotal(lista2.get(i).getSaldomoroso());

            clientestick.add(cli_ticket);

            objeto[0] = lista2.get(i).getNombre();
            objeto[1] = lista2.get(i).getApellido();
            objeto[2] = lista2.get(i).getSaldopagado();
            objeto[3] = lista2.get(i).getSaldodebe();
            objeto[4] = lista2.get(i).getSaldomoroso();
            objeto[5] = 0.0;
            objeto[6] = lista2.get(i).getFechalimitepago();
            objeto[7] = lista2.get(i).getSaldomoroso();
            objeto[8] = lista2.get(i).getNrocuota();
            modelo3.addRow(objeto);

            tablaticket.setModel(modelo3);
        }
        
      

        double porcpago = Double.parseDouble(porcentajepago.getText());
        double porcentaje = sumar * porcpago;
        porcentajecobrador.setText("$" + Double.toString(porcentaje));

        Double TotalPagarCobrador = porcentaje + (Double.parseDouble(nafta.getText()));
        TotalCobrador.setText("$ " + Double.toString(TotalPagarCobrador));
    }

    void limpiartablatickect() {
        for (int i = 0; i < modelo3.getRowCount(); i++) {
            modelo3.removeRow(i);
            i = i - 1;
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser Desde;
    private javax.swing.JButton GenerarTicketAuto;
    private javax.swing.JLabel TotalCobrador;
    private javax.swing.JButton btnImprimirTicket;
    private javax.swing.JButton btneliminar;
    private javax.swing.JLabel fechahoy;
    private com.toedter.calendar.JDateChooser hasta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel nada;
    private javax.swing.JTextField nafta;
    private javax.swing.JLabel porcentajecobrador;
    private javax.swing.JTextField porcentajepago;
    private javax.swing.JTable tablaticket;
    // End of variables declaration//GEN-END:variables
}
