/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Vistas;

import Modelo.Cliente;
import Modelo.Cuota;
import Modelo.Cuotaimpresion;
import Modelo.Prestamo;
import ModeloDao.ClienteDao;
import ModeloDao.CuotaDao;
import ModeloDao.PrestamoDao;
import configuracion.ColorearFilas;
import configuracion.ColorearHeader;
import configuracion.ColorearHeaderCuotaTikect;
import configuracion.Fecha;
import configuracion.FechaNueva;
import java.awt.Color;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.data.JRBeanCollectionDataSource;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author santi
 */
public class NuevoPrestamo extends javax.swing.JInternalFrame {
    
    ClienteDao clidao = new ClienteDao();
    PrestamoDao prestamoDao = new PrestamoDao();
    CuotaDao cuotadao = new CuotaDao();
    Prestamo prestamo = new Prestamo();
    Cliente cliente = new Cliente();
    Cuota cuota = new Cuota();
    
    String fechaImpresion;
    ArrayList<Cuotaimpresion> Listaimpresion = new ArrayList();
    List<Cliente> listaclientes = clidao.Listar();
    
    double totalpagar;
    double intereses;
    int cantidadcuotas;
    double montoprestado;
    DefaultTableModel modelo = new DefaultTableModel();
    String fechaing;
    FechaNueva fechacalculada;
    ColorearHeader CH = new ColorearHeader();
    ColorearFilas colorear = new ColorearFilas();
    String formapago;
    int id;
     ColorearHeaderCuotaTikect ColorHeaderTicket = new ColorearHeaderCuotaTikect();
    
    public NuevoPrestamo() {
        initComponents();
        Fecha fec = new Fecha(); //instanciamos la clase fecha y obtenemos en forma de string
        listar();
        String fecact = fec.Fecha();
        
        fechaactual.setText(fecact);
        
        tablacuotas.setRowHeight(24);
        
        GenerarSerie(); // genereramos el numero de prestamo
        seriecliente();
        bloquearbotones();// generamos el numero de cliente
        // bloqueamos los botones segun lo seleccionado
        txtnrocliente.setForeground(Color.blue);
        
        tablacuotas.getTableHeader().setDefaultRenderer(CH);
        tablacuotas.setDefaultRenderer(tablacuotas.getColumnClass(0), colorear);
        tablaclientes.getTableHeader().setDefaultRenderer(ColorHeaderTicket);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        fechaactual = new javax.swing.JLabel();
        LabelNroPrestamo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        txtnombre = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtapellido = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtemail = new javax.swing.JTextField();
        txtdni = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txttelefono = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtdireccion = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        txtnrocliente = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        txtmonto = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        Cboxformapago = new javax.swing.JComboBox<>();
        jLabel19 = new javax.swing.JLabel();
        fechapago = new com.toedter.calendar.JDateChooser();
        JCBOXCANTCUO = new javax.swing.JComboBox<>();
        CantidadCuotasMensuales = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtmontomensual = new javax.swing.JTextField();
        btnGenerarCuota = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        txtdnibuscar = new javax.swing.JTextField();
        btnBuscarCliente = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaclientes = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablacuotas = new javax.swing.JTable();
        jLabel15 = new javax.swing.JLabel();
        txttotalpagar = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        MONTODECUOTA = new javax.swing.JTextField();
        btngenerarprestamo = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        BtnImprimir = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setResizable(true);
        setTitle("nuevo prestamo");
        setFont(new java.awt.Font("Leelawadee UI", 0, 18)); // NOI18N

        jPanel1.setBackground(new java.awt.Color(153, 153, 255));

        jLabel2.setFont(new java.awt.Font("Lucida Console", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Fecha:");

        jLabel3.setFont(new java.awt.Font("Lucida Console", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Nro Prestamo:");

        fechaactual.setFont(new java.awt.Font("Lucida Console", 0, 18)); // NOI18N
        fechaactual.setText("22/10/2021");

        LabelNroPrestamo.setFont(new java.awt.Font("Lucida Console", 0, 18)); // NOI18N
        LabelNroPrestamo.setText("00001");

        jLabel1.setFont(new java.awt.Font("Lucida Console", 0, 18)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/registrocobro2.png"))); // NOI18N
        jLabel1.setText("Nuevo Prestamo");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(fechaactual)
                .addGap(32, 32, 32)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(LabelNroPrestamo, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(95, 95, 95))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fechaactual)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(LabelNroPrestamo)
                    .addComponent(jLabel1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "DATOS CLIENTES", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Leelawadee UI", 1, 11))); // NOI18N
        jPanel2.setFont(new java.awt.Font("Leelawadee UI", 0, 14)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Leelawadee UI", 0, 14)); // NOI18N
        jLabel4.setText("Nombre:");

        txtnombre.setFont(new java.awt.Font("Leelawadee UI", 0, 18)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Leelawadee UI", 0, 14)); // NOI18N
        jLabel5.setText("Apellido:");

        txtapellido.setFont(new java.awt.Font("Leelawadee UI", 0, 18)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Leelawadee UI", 0, 14)); // NOI18N
        jLabel6.setText("Dni:");

        jLabel7.setFont(new java.awt.Font("Leelawadee UI", 0, 14)); // NOI18N
        jLabel7.setText("Email:");

        txtemail.setFont(new java.awt.Font("Leelawadee UI", 0, 18)); // NOI18N
        txtemail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtemailActionPerformed(evt);
            }
        });

        txtdni.setFont(new java.awt.Font("Leelawadee UI", 0, 18)); // NOI18N
        txtdni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtdniActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Leelawadee UI", 0, 14)); // NOI18N
        jLabel8.setText("Telefono:");

        txttelefono.setFont(new java.awt.Font("Leelawadee UI", 0, 18)); // NOI18N

        jLabel9.setFont(new java.awt.Font("Leelawadee UI", 0, 14)); // NOI18N
        jLabel9.setText("Direccion:");

        txtdireccion.setFont(new java.awt.Font("Leelawadee UI", 0, 18)); // NOI18N

        jLabel21.setFont(new java.awt.Font("Leelawadee UI", 0, 14)); // NOI18N
        jLabel21.setText("Nro cliente: ");

        txtnrocliente.setFont(new java.awt.Font("Leelawadee UI", 0, 18)); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(txtdireccion)
                                .addGap(18, 18, 18))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(txtnombre, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE))
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(11, 11, 11)
                                        .addComponent(jLabel5))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(txtapellido, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(txtdni, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtemail, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtnrocliente, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel21))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(txttelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(100, Short.MAX_VALUE))))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtnombre, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtapellido, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtdni, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtemail, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel21)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtdireccion)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtnrocliente)
                        .addComponent(txttelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), " DATOS PRESTAMO", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Leelawadee UI", 1, 11))); // NOI18N
        jPanel3.setFont(new java.awt.Font("Leelawadee UI", 0, 14)); // NOI18N

        jLabel10.setFont(new java.awt.Font("Leelawadee UI", 0, 14)); // NOI18N
        jLabel10.setText("monto semanal:");

        txtmonto.setFont(new java.awt.Font("Leelawadee UI", 0, 14)); // NOI18N
        txtmonto.setText("50000");
        txtmonto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtmontoActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Leelawadee UI", 0, 14)); // NOI18N
        jLabel11.setText("Cuotas semanales:");

        jLabel14.setFont(new java.awt.Font("Leelawadee UI", 0, 14)); // NOI18N
        jLabel14.setText("Forma Pago:");

        Cboxformapago.setFont(new java.awt.Font("Lucida Console", 0, 14)); // NOI18N
        Cboxformapago.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Semanal", "Mensual" }));
        Cboxformapago.setBorder(null);
        Cboxformapago.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                CboxformapagoItemStateChanged(evt);
            }
        });

        jLabel19.setFont(new java.awt.Font("Lucida Console", 0, 14)); // NOI18N
        jLabel19.setText("Fecha Pago:");

        JCBOXCANTCUO.setFont(new java.awt.Font("Leelawadee UI", 0, 14)); // NOI18N
        JCBOXCANTCUO.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "4", "6", "8", "10", "12", "14", "16", "18", "20", "22", "24", "26", "28", "30", "32", "34", "36", "38", "40", "42", "44", "46", "48" }));

        CantidadCuotasMensuales.setFont(new java.awt.Font("Leelawadee UI", 0, 14)); // NOI18N
        CantidadCuotasMensuales.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));

        jLabel12.setFont(new java.awt.Font("Leelawadee UI", 0, 14)); // NOI18N
        jLabel12.setText("Cuotas mensuales:");

        jLabel13.setFont(new java.awt.Font("Leelawadee UI", 0, 14)); // NOI18N
        jLabel13.setText(" Monto Mensual:");

        txtmontomensual.setFont(new java.awt.Font("Leelawadee UI", 0, 14)); // NOI18N
        txtmontomensual.setText("15000");

        btnGenerarCuota.setBackground(new java.awt.Color(102, 255, 102));
        btnGenerarCuota.setFont(new java.awt.Font("Leelawadee UI", 0, 11)); // NOI18N
        btnGenerarCuota.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/registro4.png"))); // NOI18N
        btnGenerarCuota.setText("generar cuotas");
        btnGenerarCuota.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnGenerarCuota.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnGenerarCuota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerarCuotaActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(255, 204, 102));
        jButton2.setText("Agregar Clausulas");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(txtmonto, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(txtmontomensual, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(CantidadCuotasMensuales, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(JCBOXCANTCUO, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLabel12))
                .addGap(59, 59, 59)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(fechapago, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Cboxformapago, javax.swing.GroupLayout.Alignment.LEADING, 0, 252, Short.MAX_VALUE))
                    .addComponent(jLabel19)
                    .addComponent(jLabel14))
                .addGap(38, 38, 38)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnGenerarCuota, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11)
                            .addComponent(jLabel19))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(fechapago, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtmonto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(JCBOXCANTCUO, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel12)
                                        .addComponent(jLabel14))
                                    .addComponent(jLabel13))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(CantidadCuotasMensuales, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(Cboxformapago, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE))
                                    .addComponent(txtmontomensual)))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnGenerarCuota)))
                .addContainerGap())
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "BUSCAR CLIENTE", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Leelawadee UI", 1, 11))); // NOI18N

        txtdnibuscar.setFont(new java.awt.Font("Lucida Bright", 1, 16)); // NOI18N
        txtdnibuscar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 102, 255), 1, true));

        btnBuscarCliente.setBackground(new java.awt.Color(0, 102, 204));
        btnBuscarCliente.setFont(new java.awt.Font("Leelawadee UI", 0, 14)); // NOI18N
        btnBuscarCliente.setForeground(new java.awt.Color(255, 255, 255));
        btnBuscarCliente.setText("Buscar Cliente");
        btnBuscarCliente.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnBuscarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarClienteActionPerformed(evt);
            }
        });

        tablaclientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "nombre", "apellido", "telefono"
            }
        ));
        tablaclientes.setRowHeight(23);
        tablaclientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaclientesMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tablaclientes);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btnBuscarCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane2)
                    .addComponent(txtdnibuscar))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtdnibuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnBuscarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "DATOS DE CUOTAS", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Leelawadee UI", 1, 11))); // NOI18N

        tablacuotas.setFont(new java.awt.Font("Leelawadee UI", 0, 14)); // NOI18N
        tablacuotas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "NRO PRESTAMO", "NRO CUOTA", "MONTO CUOTA", "FECHA DE PAGO"
            }
        ));
        tablacuotas.setGridColor(new java.awt.Color(0, 153, 255));
        tablacuotas.setMinimumSize(new java.awt.Dimension(60, 10));
        tablacuotas.setSelectionBackground(new java.awt.Color(0, 153, 204));
        jScrollPane1.setViewportView(tablacuotas);

        jLabel15.setFont(new java.awt.Font("Leelawadee UI", 0, 18)); // NOI18N
        jLabel15.setText("Monto total a pagar:");

        txttotalpagar.setBackground(new java.awt.Color(240, 240, 240));
        txttotalpagar.setFont(new java.awt.Font("Leelawadee UI", 0, 24)); // NOI18N
        txttotalpagar.setForeground(new java.awt.Color(255, 51, 51));
        txttotalpagar.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 51, 51)));

        jLabel17.setFont(new java.awt.Font("Leelawadee UI", 0, 18)); // NOI18N
        jLabel17.setText("Monto por cuota: ");

        MONTODECUOTA.setBackground(new java.awt.Color(240, 240, 240));
        MONTODECUOTA.setFont(new java.awt.Font("Leelawadee UI", 0, 24)); // NOI18N
        MONTODECUOTA.setForeground(new java.awt.Color(255, 51, 51));
        MONTODECUOTA.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 0, 51)));

        btngenerarprestamo.setBackground(new java.awt.Color(204, 204, 255));
        btngenerarprestamo.setFont(new java.awt.Font("Leelawadee UI", 0, 12)); // NOI18N
        btngenerarprestamo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/checkin1.png"))); // NOI18N
        btngenerarprestamo.setText("REGISTRAR PRESTAMO");
        btngenerarprestamo.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btngenerarprestamo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btngenerarprestamo.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        btngenerarprestamo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btngenerarprestamo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btngenerarprestamoActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(204, 204, 255));
        jButton1.setFont(new java.awt.Font("Leelawadee UI", 0, 12)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/cancelar4.png"))); // NOI18N
        jButton1.setText("CANCELAR");
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        BtnImprimir.setFont(new java.awt.Font("Leelawadee UI", 0, 14)); // NOI18N
        BtnImprimir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/imprimir3.png"))); // NOI18N
        BtnImprimir.setText("IMPRIMIR");
        BtnImprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnImprimirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel15)
                    .addComponent(btngenerarprestamo)
                    .addComponent(jLabel17))
                .addGap(35, 35, 35)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(BtnImprimir, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(MONTODECUOTA, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txttotalpagar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 197, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 676, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(95, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(BtnImprimir, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txttotalpagar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel17)
                            .addComponent(MONTODECUOTA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btngenerarprestamo, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addGap(21, 21, 21))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtemailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtemailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtemailActionPerformed

    private void txtdniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtdniActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtdniActionPerformed

    private void btnBuscarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarClienteActionPerformed
        buscarcliente();
    }//GEN-LAST:event_btnBuscarClienteActionPerformed

    private void btnGenerarCuotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerarCuotaActionPerformed
        limpiartablacuota();
        generarcuota();
    }//GEN-LAST:event_btnGenerarCuotaActionPerformed

    private void txtmontoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtmontoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtmontoActionPerformed

    private void btngenerarprestamoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btngenerarprestamoActionPerformed
        generarprestamo();
    }//GEN-LAST:event_btngenerarprestamoActionPerformed

    private void CboxformapagoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_CboxformapagoItemStateChanged
        bloquearbotones();
    }//GEN-LAST:event_CboxformapagoItemStateChanged

    private void BtnImprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnImprimirActionPerformed
        try {
            JasperReport reporte = (JasperReport) JRLoader.loadObjectFromFile("C:\\Users\\santi\\Documents\\NetBeansProjects\\Prestamin\\src\\Reportes\\NuevoPrestamo.jasper");
            Map parametro = new HashMap();
            parametro.put("nombre", txtnombre.getText());
            parametro.put("apellido", txtapellido.getText());
            parametro.put("telefono", txttelefono.getText());
            parametro.put("nroprestamo", LabelNroPrestamo.getText());
            parametro.put("fecharegistro", fechaactual.getText());
            parametro.put("montosolicitado", montoprestado);
            parametro.put("cantidadcuotas", cantidadcuotas);
            parametro.put("formapago", formapago);
            parametro.put("montocuota", MONTODECUOTA.getText());
            
            parametro.put("fondoimagen", "C:\\Users\\santi\\Documents\\NetBeansProjects\\Prestamin\\src\\Iconos\\Prestamin2.png");
            JasperPrint pirnt = JasperFillManager.fillReport(reporte, parametro, new JRBeanCollectionDataSource(Listaimpresion));
            JasperViewer.viewReport(pirnt, false);
        } catch (JRException ex) {
            Logger.getLogger(RegistrarCobro2.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_BtnImprimirActionPerformed

    private void tablaclientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaclientesMouseClicked
        int seleccionar = tablaclientes.getSelectedRow();
        id = Integer.parseInt((tablaclientes.getValueAt(seleccionar, 0).toString()));
        Cliente cli = new Cliente();
        cli = clidao.BuscarClientePorId(id);
        txtnombre.setText(cli.getNombre());
        txtapellido.setText(cli.getApellido());
        txttelefono.setText(cli.getTelefono());
        txtemail.setText(cli.getEmail());
        txtdireccion.setText(cli.getDireccion());
        txtdni.setText(cli.getDni());
        txtnrocliente.setText(Integer.toString(cli.getId()));
        

    }//GEN-LAST:event_tablaclientesMouseClicked

    //public String calcularfecha(){
    //}
    public void generarcuota() {
        SimpleDateFormat sdf = new SimpleDateFormat("dd-MM-yyyy");
        Fecha fecha = new Fecha();
        FechaNueva fecnueva = new FechaNueva();
        
        int SemanaMes = Cboxformapago.getSelectedIndex();
        
        if (SemanaMes == 0) {
            
            montoprestado = Double.parseDouble(txtmonto.getText());
            prestamo.setFormapago("semanal");
            formapago = "semanal";
            cantidadcuotas = Integer.parseInt((String) JCBOXCANTCUO.getSelectedItem());

            //MONTODECUOTA.setText((txtmontocuota.getText())); 
            double monto = cuotadao.CalcularCuotaSemanal(cantidadcuotas, montoprestado);
            
            intereses = cuotadao.asignarinteresessemanales(cantidadcuotas);
            String formapago = (String) Cboxformapago.getSelectedItem();
            String dia = Integer.toString(fechapago.getCalendar().get(Calendar.DAY_OF_MONTH));
            String mes = Integer.toString(fechapago.getCalendar().get(Calendar.MONTH) + 1);
            String year = Integer.toString(fechapago.getCalendar().get(Calendar.YEAR));
            MONTODECUOTA.setText(Double.toString(monto));
            fecnueva.setAño(year);
            fecnueva.setDia(dia);
            fecnueva.setMes(mes);
            
            fechaing = dia + "-" + mes + "-" + year;
            
            totalpagar = prestamoDao.TotalPagarSemanal(cantidadcuotas, montoprestado);
            txttotalpagar.setText((Double.toString(totalpagar)));
            modelo = (DefaultTableModel) tablacuotas.getModel();

//          
            int item = 0;
            for (int i = 0; i < cantidadcuotas; i++) {
                Cuotaimpresion cuoimp = new Cuotaimpresion();
                item = item + 1;
                ArrayList lista = new ArrayList();
                lista.add(LabelNroPrestamo.getText());
                lista.add(item);
                lista.add(monto);
                lista.add(fechaing);
                cuoimp.setNroprestamo(LabelNroPrestamo.getText());
                cuoimp.setMonto(Double.toString(monto));
                cuoimp.setFechainicioprestamo(fechaing);
                cuoimp.setNrocuota(Integer.toString(item));
                Listaimpresion.add(cuoimp);
                Object[] ob = new Object[4];
                ob[0] = lista.get(0);
                ob[1] = lista.get(1);
                ob[2] = lista.get(2);
                ob[3] = lista.get(3);
                
                modelo.addRow(ob);
                tablacuotas.setModel(modelo);
                
                fechacalculada = fecha.calcularfechapagosemanal(fecnueva); // obtengo las nueva fecha pago calculada y sus variables dia ano mes

                dia = fechacalculada.getDia();
                mes = fechacalculada.getMes();
                year = fechacalculada.getAño();
                
                fecnueva.setAño(year);
                fecnueva.setDia(dia);
                fecnueva.setMes(mes);
                
                fechaing = dia + "-" + mes + "-" + year;
            }
            
        } else {
            montoprestado = Double.parseDouble(txtmontomensual.getText());
            prestamo.setFormapago("mensual");
            cantidadcuotas = Integer.parseInt((String) CantidadCuotasMensuales.getSelectedItem());
            formapago = "mensual";
            intereses = cuotadao.asignarinteresesmenuales(cantidadcuotas);
            //MONTODECUOTA.setText((txtmontocuota.getText())); 
            double monto = cuotadao.CalcularCuotaMensual(cantidadcuotas, montoprestado);

            //Double intereses = Double.parseDouble(txtintereses.getText());
            String formapago = (String) Cboxformapago.getSelectedItem();
            String dia = Integer.toString(fechapago.getCalendar().get(Calendar.DAY_OF_MONTH));
            String mes = Integer.toString(fechapago.getCalendar().get(Calendar.MONTH) + 1);
            String year = Integer.toString(fechapago.getCalendar().get(Calendar.YEAR));
            MONTODECUOTA.setText(Double.toString(monto));
            fecnueva.setAño(year);
            fecnueva.setDia(dia);
            fecnueva.setMes(mes);
            
            fechaing = dia + "-" + mes + "-" + year;
            
            totalpagar = prestamoDao.TotalPagarMensual(cantidadcuotas, montoprestado);
            txttotalpagar.setText((Double.toString(totalpagar)));
            modelo = (DefaultTableModel) tablacuotas.getModel();

//
            int item = 0;
            for (int i = 0; i < cantidadcuotas; i++) {
                Cuotaimpresion cuoimp = new Cuotaimpresion();
                item = item + 1;
                ArrayList lista = new ArrayList();
                lista.add(LabelNroPrestamo.getText());
                lista.add(item);
                lista.add(monto);
                lista.add(fechaing);
                cuoimp.setNroprestamo(LabelNroPrestamo.getText());
                cuoimp.setMonto(Double.toString(monto));
                cuoimp.setFechainicioprestamo(fechaing);
                cuoimp.setNrocuota(Integer.toString(item));
                
                Listaimpresion.add(cuoimp);
                Object[] ob = new Object[4];
                ob[0] = lista.get(0);
                ob[1] = lista.get(1);
                ob[2] = lista.get(2);
                ob[3] = lista.get(3);
                
                modelo.addRow(ob);
                tablacuotas.setModel(modelo);
                
                fechacalculada = fecha.calcularfechapagomensual(fecnueva); // obtengo las nueva fecha pago calculada y sus variables dia ano mes

                dia = fechacalculada.getDia();
                mes = fechacalculada.getMes();
                year = fechacalculada.getAño();
                
                fecnueva.setAño(year);
                fecnueva.setDia(dia);
                fecnueva.setMes(mes);
                
                fechaing = dia + "-" + mes + "-" + year;
            }
        }
        
    }
    
    void buscarcliente() {
        String dnicli = txtdnibuscar.getText();
        
        if (txtdnibuscar.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Udted debe ingresar el dni del cliente");
        } else {
            Cliente cli = clidao.BuscarCliente(dnicli);
            if (cli.getDni() != null) {
                String serie = Integer.toString(cli.getId());
                txtnrocliente.setText("00000" + serie);
                txtnrocliente.setForeground(Color.BLACK);
                txtnombre.setText(cli.getNombre());
                txtapellido.setText(cli.getApellido());
                txtdni.setText(cli.getDni());
                txtdireccion.setText(cli.getDireccion());
                txttelefono.setText(cli.getTelefono());
                txtemail.setText(cli.getEmail());
            } else {
                JOptionPane.showMessageDialog(this, "El cliente no esta en la base de datos");
                seriecliente();
                txtnrocliente.setForeground(Color.blue);
                
                txtnombre.setText("");
                txtapellido.setText("");
                txtdni.setText("");
                txtdireccion.setText("");
                txttelefono.setText("");
                txtemail.setText("");
            }
        }
        
    }
    
    void seriecliente() {
        String serie = clidao.IdCliente();
        
        if (serie == null) {
            txtnrocliente.setText("0000" + 1);
        } else {
            int inc = Integer.parseInt(serie) + 1;
            txtnrocliente.setText("0000" + inc);
        }
    }
    
    void GenerarSerie() {
        String serie = prestamoDao.GenerarSerie();
        
        if (serie == null) {
            LabelNroPrestamo.setText("000001");
        } else {
            int inc = Integer.parseInt(serie);
            inc = inc + 1;
            LabelNroPrestamo.setText("00000" + inc);
            
        }
    }
    
    public void generarprestamo() {
        Date fechainicioprestamo = new Date();
        Date fechapago = new Date();
        java.sql.Date fechaN = null;
        java.sql.Date fechaIn = null;
        String estado = "vigente";
        SimpleDateFormat formato = new SimpleDateFormat("dd-MM-yyyy");

        //DATOS DEL PRESTAMO
        double monto = montoprestado;
        //Double.parseDouble(MONTODECUOTA.getText());
        //cantidadcuotas = (JCBOXCANTCUO.getSelectedIndex());
        //double intereses = cuotadao.asignarintereses(cantidadcuotas);
        try {
            fechapago = formato.parse(fechaing);
            fechaN = new java.sql.Date(fechapago.getTime()); // lo convertimos a un Date para la bd
        } catch (ParseException ex) {
            Logger.getLogger(NuevoPrestamo.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, "error al procesar la fecha fechapago");
            
        }
        
        try {
            fechainicioprestamo = formato.parse(fechaactual.getText());
            fechaIn = new java.sql.Date(fechainicioprestamo.getTime());
            
        } catch (ParseException ex) {
            Logger.getLogger(NuevoPrestamo.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, "error al procesar la fecha inicio prestamo");
        }

        //datos del prestamo
        prestamo.setEstado(estado);
        prestamo.setFecha_inicio(fechaIn);
        prestamo.setIntereses(intereses);
        prestamo.setMontoprestado(monto);
        prestamo.setCantidadcuotas(cantidadcuotas);
        prestamo.setTotalpagar(totalpagar);
        
        String dnicli = txtdnibuscar.getText();
        Cliente cli = clidao.BuscarCliente(dnicli);
        int idcliente = Integer.parseInt(txtnrocliente.getText());
        prestamo.setId_cliente(idcliente);
        
        prestamoDao.GuardarPrestamo(prestamo); // Se guarda el prestamo en la bd

        //Datos Del Cliente
        if (cli.getDni() == null) {
            
            cliente = new Cliente();
            String nombre = txtnombre.getText();
            String apellido = txtapellido.getText();
            String dni = txtdni.getText();
            String email = txtemail.getText();
            String telefono = txttelefono.getText();
            String direccion = txtdireccion.getText();
            
            cliente.setId(idcliente);
            cliente.setNombre(nombre);
            cliente.setApellido(apellido);
            cliente.setDireccion(direccion);
            cliente.setDni(dni);
            cliente.setEmail(email);
            cliente.setTelefono(telefono);
            
            clidao.GuardarCliente(cliente);
            
        }

        //DATOS DE LA CUOTA
        for (int i = 0; i < tablacuotas.getRowCount(); i++) {
            // recorremos la tabla para guardar los datos de la cuota
            java.sql.Date fechax = null;
            Date fechapagar = new Date();
            
            int nrocuota = Integer.parseInt(tablacuotas.getValueAt(i, 1).toString());
            double monto_cuota = Double.parseDouble(MONTODECUOTA.getText());
            SimpleDateFormat sf = new SimpleDateFormat("dd-MM-yyyy"); //formato date para la base de datos
            String fecha = tablacuotas.getValueAt(i, 3).toString();
            try {
                fechapagar = sf.parse(fecha); // hicimos el parseo pero esta fecha esta en tipo java.util.date
                fechax = new java.sql.Date(fechapagar.getTime()); // lo pasamos a java.sql.date
            } catch (ParseException ex) {
                Logger.getLogger(NuevoPrestamo.class.getName()).log(Level.SEVERE, null, ex);
            }
            String estadocuota = "PENDIENTE";
            
            cuota.setIdprestamo(Integer.parseInt(LabelNroPrestamo.getText()));
            cuota.setMonto(monto_cuota);
            
            cuota.setFechapago(fechax);
            cuota.setNumero_cuota(nrocuota);
            cuota.setEstadocuota(estadocuota);
            
            cuotadao.GuardarCuota(cuota);
            
        }
        
        JOptionPane.showMessageDialog(this, "EL PRESTAMO SE REALIZO CON EXITO...!!!");
        
    }
    
    void bloquearbotones() {
        if (Cboxformapago.getSelectedIndex() == 0) {
            txtmontomensual.setEnabled(false);
            CantidadCuotasMensuales.setEnabled(false);
            txtmonto.setEnabled(true);
            JCBOXCANTCUO.setEnabled(true);
        }
        
        if (Cboxformapago.getSelectedIndex() == 1) {
            txtmonto.setEnabled(false);
            JCBOXCANTCUO.setEnabled(false);
            txtmontomensual.setEnabled(true);
            CantidadCuotasMensuales.setEnabled(true);
        }
        
    }
    
    void limpiartablacuota() {
        for (int i = 0; i < modelo.getRowCount(); i++) {
            modelo.removeRow(i);
            i = i - 1;
        }
    }
    
    void listar() {
        modelo = (DefaultTableModel) tablaclientes.getModel();
        Object[] objeto = new Object[4];
        for (int i = 0; i < listaclientes.size(); i++) {
            objeto[1] = listaclientes.get(i).getNombre();
            objeto[2] = listaclientes.get(i).getApellido();
            
            objeto[0] = listaclientes.get(i).getId();
            objeto[3] = listaclientes.get(i).getTelefono();
            
            modelo.addRow(objeto);
            
        }
        tablaclientes.setModel(modelo);
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnImprimir;
    private javax.swing.JComboBox<String> CantidadCuotasMensuales;
    private javax.swing.JComboBox<String> Cboxformapago;
    private javax.swing.JComboBox<String> JCBOXCANTCUO;
    private javax.swing.JLabel LabelNroPrestamo;
    private javax.swing.JTextField MONTODECUOTA;
    private javax.swing.JButton btnBuscarCliente;
    private javax.swing.JButton btnGenerarCuota;
    private javax.swing.JButton btngenerarprestamo;
    private javax.swing.JLabel fechaactual;
    private com.toedter.calendar.JDateChooser fechapago;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tablaclientes;
    private javax.swing.JTable tablacuotas;
    private javax.swing.JTextField txtapellido;
    private javax.swing.JTextField txtdireccion;
    private javax.swing.JTextField txtdni;
    private javax.swing.JTextField txtdnibuscar;
    private javax.swing.JTextField txtemail;
    private javax.swing.JTextField txtmonto;
    private javax.swing.JTextField txtmontomensual;
    private javax.swing.JTextField txtnombre;
    private javax.swing.JTextField txtnrocliente;
    private javax.swing.JTextField txttelefono;
    private javax.swing.JTextField txttotalpagar;
    // End of variables declaration//GEN-END:variables
}
